### PR TITLE
MetaImageHeader file for a single raw image

### PR DESCRIPTION
**Pull request by MichaelColonel**
Dear developers,

Meta header information allows easier loading of raw image for further processing (e.g. in ITK), not just raw import in ImageJ. It could be useful for somebody.

### CODE REVIEW

**Comment by golosio** [comment]
Dear Michael,
the use of the header is optional or mandatory? Will it be still possible to produce raw images without header as output?

**Comment by MichaelColonel** [comment]
Optional. The MetaImage header file didn't modify the original raw data. This PR creates additional .mhd text file, original raw data can be used as before.

**Comment by tschoonj** [comment]
Generating these files should be optional in my opinion. Can you add a flag for this?

Thanks!

**Comment by MichaelColonel** [comment]
Greetings,

Do you mean like AsciiFlag or HeaderFlag? I will try.

https://github.com/golosio/xrmc/blob/725512d7b70167a3aede2d50a7dcec4394db5eee/src/detector/xrmc_detector.h#L79-#lL80

**Comment by tschoonj** [comment]
Something like that would indeed be great. Thanks!

**Comment by tschoonj** [comment]
Thanks @MichaelColonel ! That looks good.

@golosio do you have any further comments?

**Comment by MichaelColonel** [comment]
Should i squash commits in this PR into one commit?

**Comment by tschoonj** [comment]
As you wish...

**Comment by MichaelColonel** [comment]
Commits have been squashed into one.

**Comment by tschoonj** [comment]
Thanks for your contribution @MichaelColonel !

**Pull request merged**
